#!/usr/bin/env python
import datetime

from horetu import annotate, horetu

@annotate(str, int, datetime.datetime.fromtimestamp)
def f(x, n = 8, *dates):
    for date in dates:
        print('%s: %s' % (x, date + datetime.timedelta(hours = n)))

