#!/usr/bin/env python3
from collections import namedtuple

import horetu


def main(f: ('tuple', 'dict', 'namedtuple', 'obj'),
         n:int=int(1e8), length=2):
    '''
    Run with "time" to see that dict lookups are slightly faster in this case.
    '''
    if f == 'obj':
        x = None
        for i in range(n):
            x
    elif f == 'namedtuple':
        if length != 2:
            raise ValueError('Length must be 2 for namedtuple.')
        XS = namedtuple('X', ['a', 'b'])
        xs = XS(None, None)
        for i in range(n):
            xs.a
    else:
        if f == 'tuple':
            xs = tuple(range(length))
        elif f == 'dict':
            xs = dict({i: None for i in range(length)})
        for i in range(n):
            xs[0]


if __name__ == '__main__':
    horetu.horetu(main)
