#!/usr/bin/env python
import requests
from horetu import horetu

def proxy(f):
    def g(url:str, *args:str):
        kwargs = {}
        for arg in args:
            k, v = arg.split('=')
            kwargs[k] = eval(v)
        print(f(url, **kwargs).text)
    return g

methods = ['get', 'post', 'put', 'patch', 'delete']
if __name__ == '__main__':
    commands = {method: proxy(getattr(requests, method)) for method in methods}
    horetu(commands, name='requests',
           description='Make requests with python-requests.')
