#!/usr/bin/env python
import requests
from horetu import horetu

def proxy(f):
    def g(url:str, params:str, *args:str):
        kwargs = {}
        for arg in args:
            k, _, v = a.split('=')
            kwargs[k] = v
        return f(url, params=params, **kwargs)
    return g

methods = ['get', 'post', 'put', 'patch', 'delete']
if __name__ == '__main__':
    commands = {method: proxy(getattr(requests, method)) for method in methods}
    horetu(commands, name='requests',
           description='Make requests with python-requests.')
