#!/usr/bin/env python
import re
import horetu

def launch_spacecraft(to_planet, from_planet='earth', cargo='8000kg'):
    '''
    Launch a spacecraft.

    :param to_planet: Planet we are launching to
    :param from_planet: Planet we are launching from (Default is Earth.)
    :param cargo: Cargo, in kilograms (kg) or tonnes (t)
    '''
    m = re.match(r'^([.0-9]+)(kg|t|)$')
    if not m:
        raise ValueError('Cargo should be formatted like "3.5t" or "1201kg".')
    
    if m.group(2) == 't':
        quantity = int(round(float(m.group(1)) * 1000))
    else:
        quantity = int(m.group(1))
    msg = 'Launching spacecraft with %s kg cargo from %s to %s'
    print(msg % (quantity, from_planet, to_planet))

horetu.horetu(launch_spacecraft)
